### ISSUE TITLE
Error when running code on Windows

### ISSUE THREAD

**Issue by ghost** [hugolgst/rich-go#1]
I'm having a weird crash when running the following code:
```
package main

import "github.com/ananagame/rich-go/client"

//Client IDs of the Discord applications
const (
	// CodingActivity = "483209655728865290"
	GamingActivity = "483148659937116168"
)

func main() {
	client.Login(GamingActivity)
	client.SetActivity(client.Activity{State: "Gaming", Details: "Playing some games"})
}
```
The crash is:
```
panic: dial unix C:\Users\nutsack\AppData\Local\Temp/discord-ipc-0: socket: An address incompatible with the requested protocol was used.ddress incompatible with the requested protocol was used.

goroutine 1 [running]:
github.com/ananagame/rich-go/ipc.OpenSocket()
        C:/Users/nutsack/go/src/github.com/ananagame/rich-go/ipc/ipc.go:32 +0x14bgithub.com/ananagame/rich-go/client.Login(0x53a514, 0x12)
        C:/Users/nutsack/go/src/github.com/ananagame/rich-go/client/client.go:46 +0xff
main.main()        C:/Users/nutsack/Desktop/Coding/Go/CustomRPC/main.go:12 +0x3d
```

**Comment by donovansolms** [comment]
I've added Windows support [in my fork](https://github.com/donovansolms/rich-go)

I'd like to make a PR for this @ananagame, but there are breaking changes. Errors are returned in my fork instead of panic().

Let my know if you are Ok with that, then I'll do a PR.

**Comment by hugolgst** [comment]
Sure I'll check it

**Comment by hugolgst** [comment]
That's all good you can make a PR :)

**Comment by hugolgst** [comment]
I've added merged his fork
